import { Footer } from "@/components/Footer";
import { NavLanding } from "@/components/NavLanding";
import { Main } from "@/components/Layout";
import Head from "next/head";

export const AboutPage = () => {
  return (
    <div className="">
      <Head>
        <title>CVLAB | 关于项目</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLanding aspect="half" title="关于项目" />
      <Main>aaa</Main>
      <Footer />
    </div>
  );
};
