import { Footer } from "@/components/Footer";
import { NavLanding } from "@/components/NavLanding";
import { Main } from "@/components/Layout";
import Head from "next/head";

export const DisplayPage = () => {
  return (
    <div className="">
      <Head>
        <title>CVLAB | 项目展示</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLanding aspect="half" title="CVLAB 项目展示" />
      <Main>

      </Main>
      <Footer />
    </div>
  );
};
