import { Footer } from "@/components/Footer";
import { Main } from "@/components/Layout";
import { NavPlain } from "@/components/NavPlain";
import { PostReader } from "@/components/PostReader";
import { MDXRemoteProps } from "next-mdx-remote";
import Head from "next/head";

export const PostPage = (props: {
  postTitle: string,
  postSubtitle?: string,
  postCitation?: string,
  postAuthor?: string,
  content: MDXRemoteProps
}) => {
  return (
    <div className="">
      <Head>
        <title>西北民族大学 CVLAB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavPlain />
      <Main>
        <PostReader title={props.postTitle} content={props.content} subtitle={props.postSubtitle} citation={props.postCitation} />
      </Main>
      <Footer />
    </div>
  );
};

